// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD6D8NNficLJdj3itUpkKdNFF4HIL2QDA',
    appId: '1:348674531283:web:266a44ae059b60b5825926',
    messagingSenderId: '348674531283',
    projectId: 'codelab-3ff6a',
    authDomain: 'codelab-3ff6a.firebaseapp.com',
    storageBucket: 'codelab-3ff6a.appspot.com',
    measurementId: 'G-D36K76EWGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi_lo0YJzmj8hKb4UB8yh_KSPAOseFE_Y',
    appId: '1:348674531283:android:3a33f383e332cdbd825926',
    messagingSenderId: '348674531283',
    projectId: 'codelab-3ff6a',
    storageBucket: 'codelab-3ff6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUaZnOjYzpo7EAdjZjxAsUK6Vkxrnx_k4',
    appId: '1:348674531283:ios:d6aee76e6a681ed0825926',
    messagingSenderId: '348674531283',
    projectId: 'codelab-3ff6a',
    storageBucket: 'codelab-3ff6a.appspot.com',
    iosClientId: '348674531283-05883vr2qvm00b5ulgvmt086o4q8ln1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeLabWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUaZnOjYzpo7EAdjZjxAsUK6Vkxrnx_k4',
    appId: '1:348674531283:ios:3ae501c1eef7e977825926',
    messagingSenderId: '348674531283',
    projectId: 'codelab-3ff6a',
    storageBucket: 'codelab-3ff6a.appspot.com',
    iosClientId: '348674531283-n1o548c6hd6i13uqvvqp46seuvst71je.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeLabWeb.RunnerTests',
  );
}
